# Generated by Django 4.2.4 on 2023-10-22 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_voting', '0002_remove_vote_player_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='points',
        ),
    ]
