# Generated by Django 4.2.4 on 2023-10-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_voting', '0004_game_goal_game_match_votes_game_minuites_game_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='goal',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='match_votes',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='minuites',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
