# Generated by Django 4.2.4 on 2023-11-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floorball_voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='assists',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
